apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m0s
  chart:
    spec:
      chart: sealed-secrets
      version: '>=1.15.0-0'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
