apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
spec:
  interval: 1m
  timeout: 5m0s
  chart:
    spec:
      chart: netdata
      version: '3.x.x'
      sourceRef:
        kind: HelmRepository
        name: netdata-repo
        namespace: monitoring
      interval: 1m
  values:
    ingress:
      enabled: false
    database:
      persistence: true
      storageclass: ""
      volumesize: 4Gi
    alarms:
      persistence: true
      storageclass: ""
      volumesize: 2Gi
    #Check more at https://artifacthub.io/packages/helm/netdata/netdata/3.1.0?modal=values
    